//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerQlsvAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLSVEntities : DbContext
    {

        public QLSVEntities()
            : base("name=QLSVEntities")
        {
            /*if (string.IsNullOrEmpty(connectionName) || string.IsNullOrEmpty(schemaName))
            {
                throw new ArgumentNullException(@"connectionName and schemaName are mandatory");
            }

            _connectionName = connectionName;
            _schemaName = schemaName;*/
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();

            //Database.SetInitializer<QLSVEntities>(new System.Data.Entity.DropCreateDatabaseIfModelChanges<QLSVEntities>());

            //modelBuilder.Entity<QLSVEntities>().ToTable("SINHVIEN", _schemaName);

            //base.OnModelCreating(modelBuilder);
        }
    
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
    }
}
