//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerQlsvAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public int MaSoSinhVien { get; set; }
        public string HoTen { get; set; }
        public string NgaySinh { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<double> DiemTichLuy { get; set; }
    }
}
